### ISSUE TITLE
Error: Cannot find module './build/Release/DTraceProviderBindings'

### ISSUE THREAD

**Issue by shashkovdanil** [react-community/create-react-native-app#226] opened 2017-05-25 04:08 UTC
{ Error: Cannot find module './build/Release/DTraceProviderBindings'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/shashkov/Projects/dribbble-app/node_modules/dtrace-provider/dtrace-provider.js:17:23)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3) code: 'MODULE_NOT_FOUND' }

## Environment
* `npm ls react-native`: 0.44.0
* `npm ls expo`: 17.0.0
* `node -v`: 7.10
* `yarn`: 24.4
* `watchman version`: 4.7.0

**Comment by dikaiosune** [comment] 2017-05-25 18:19
Thanks for the report! This is a duplicate of #135, so I'll close this in favor of tracking that bug.

**Closed by dikaiosune** 2017-05-25 18:19 UTC
