### ISSUE TITLE
Problem after eject

### ISSUE THREAD

**Issue by DanielWalendzewicz** [react-community/create-react-native-app#782] opened 2018-09-28 22:11 UTC
I was creating app by create-react-native-app / npm run eject / npm run ios */android couple months ago, and I wasn't having any problems . Now I'm confused becouse i have problems after ejecting. I see that there's no index.js , could someone tell step by step what i should change in my files after ejecting to use correctly npm run ios/android? 
Thanks

**Comment by Aximem** [comment] 2018-10-01 12:33
Duplicate of #777 
This issue is really annoying and makes CRNA completely obsolete right now.

**Closed** 2018-10-03 16:16 UTC
Labels: moving-to-expo-cli
