### ISSUE TITLE
Error: You are using npm version 5.0.3. Please use an npm version that is >= 3.0.0 and < 5.0.0.

### ISSUE THREAD

**Issue by k2glyph** [react-community/create-react-native-app#277] opened 2017-06-26 15:25 UTC
**I am not able to run the project using yarn start. I didn't get any hint on this error.**

```
Error: You are using npm version 5.0.3. Please use an npm version that is >= 3.0.0 and < 5.0.0.
9:08:07 PM: Error starting packager: Error: Couldn't start project. Please fix the errors and restart the project.
    at /xdl/src/Project.js:1038:11
    at next (native)
    at step (/home/medinesh/Documents/upwork/boilerplate/node_modules/xdl/build/Project.js:1468:191)
    at /home/medinesh/Documents/upwork/boilerplate/node_modules/xdl/build/Project.js:1468:361
    at process._tickCallback (internal/process/next_tick.js:109:7)
error Command failed with exit code 1.

```

**Comment by antoniwan** [comment] 2017-06-26 20:53
Hey man,

The hint is right there: `Please use an npm version that is >= 3.0.0 and < 5.0.0.`

I just got the same issue and am thinking of going back to an earlier version of npm to be able to use this project.

Good luck!

**Comment by VladimirDev93** [comment] 2017-06-26 20:59
The project clearly states in README.md the following

**You'll need to have Node v6 or later on your machine. We strongly recommend using npm v3, v4, or a recent version of Yarn. Create React Native App does not currently work with npm v5 due to bugs in npm.**

**Comment by sixertoy** [comment] 2017-06-27 09:16
Hey!
Anyone has made tests with the latest NPM v5.0.4 ?

**Comment by sixertoy** [comment] 2017-06-27 10:25
NPM v5.0.4 seems to bring a fix
If this issues is related to 
https://github.com/npm/npm/issues/16893

Then, i've reproduced @brentvatne under 5.0.3 but it works under .4
package-lock looks good

**Comment by Noor0** [comment] 2017-06-27 11:43
Is there any way to downgrade npm except deleting and installing node?

**Comment by sixertoy** [comment] 2017-06-27 12:02
@Noor0 `npm i -g npm@x.x.x` where x.x.x is version number to

**Comment by brentvatne** [comment] 2017-06-27 16:50
thanks @sixertoy! I'll give it a try

**Comment by Monte9** [comment] 2017-06-29 20:36
Ran into this as well. Although the npm version satisfies the requirements. Not sure why I still see this error. 

```
➜  test_proj npm -v
3.10.7
```

**Comment by VladimirDev93** [comment] 2017-06-29 21:01
@Monte9 What if you do
```bash
$ npm --version 
``` 
not in the project directory, but globally?

**Comment by Monte9** [comment] 2017-06-30 00:32
Good point. tried that but it's still the same. Shows me `3.10.7`

**Comment by shkfnly** [comment] 2017-07-01 15:55
@Monte9 running `npm install npm@4.6.1` in the project directory saved me

**Comment by muescha** [comment] 2017-07-05 00:37
> Seems they have weakened the check for npm version in the latest xdl:
https://github.com/expo/xdl/commit/224cf7a925e842d61490d2ce63b3bf79f68a93f0

(comment from here: https://github.com/sysgears/apollo-universal-starter-kit/issues/221#issuecomment-3112650790)

**Comment by muescha** [comment] 2017-07-05 15:01
the `xdl` version with the fix to `WARNING` is `42.3.0` (just now it is `42.0.0`
( https://github.com/react-community/create-react-native-app/blob/master/react-native-scripts/package.json#L38 )

**Comment by dkarter** [comment] 2017-07-06 04:35
You can also add npm via yarn to this project `yarn add npm@4.6.1`

**Comment by EasonWang01** [comment] 2017-07-06 08:14
Cause `npm install npm@4.6.1` will remove all other package for npm5 in react native.
So `npm install npm@4.6.1`  then `npm install`
Or just `yarn add npm@4.6.1`

**Comment by muescha** [comment] 2017-07-06 18:16
this npm@4.6.1 is just a workaround with downgrading

**Comment by brentvatne** [comment] 2017-07-06 18:44
@muescha - not sure what you want us to do about that, our next release will remove the error message, but we absolutely needed it because too many people had issues with the project not working with npm 5. a workaround is sometimes necessary when there is buggy software in the ecosystem, like npm 5.0.0 -> npm 5.0.3.

**Comment by muescha** [comment] 2017-07-09 14:35
i understand workarounds a needed. but why workarounds when it can solved with an dependency.

when exact this error line `xdl/src/Project.js:1038:11` comes from an thrown FATAL in `xdl` version `42.0.0` and this is fixed in `42.3.0` of `xdl`  ( see https://github.com/expo/xdl/commit/224cf7a925e842d61490d2ce63b3bf79f68a93f0 )

why not upgrade the dependency of `xdl` from `42.0.0` to `42.3.0` in the `package.json`?

**Comment by asfernandes** [comment] 2017-07-10 11:46
I'm having this error but I'm running with "yarn run android", not "npm run android".

**Comment by geminiyellow** [comment] 2017-07-11 03:35
`Error: You are using npm version 5.2.0. Please use an npm version that is >= 3.0.0 and < 5.0.0.`

😞

**Comment by vinamelody** [comment] 2017-07-19 02:06
I'm already downgraded and using npm 4.6.1 globally now, but why am I still seeing `Error: You are using npm version 5.0.3. Please use an npm version that is >= 3.0.0 and < 5.0.0. Run 'npm i -g npm@4.6.1' to resolve.` ?

I tried installing npm locally like @shkfnly suggested too and it doesn't work :(

**Comment by jhannes** [comment] 2017-07-24 20:02
It seems to work with newer versions of npm. I upgraded by doing `npm install -g npm`, which installed npm 5.3.0. After this, the warning went away.

**Comment by brentvatne** [comment] 2017-07-24 22:19
this is fixed in the latest version of react-native-scripts, you can update your project to it if you like, or create a new project and you will get it automatically

**Closed by brentvatne** 2017-07-24 22:19 UTC

**Comment by dmnd** [comment] 2017-10-01 18:24
@brentvatne I get this error using 1.5.0 of `react-native-scripts`. Is there a newer version?

It's confusing because I'm trying to use yarn, not npm:

```
$ yarn ios
yarn ios v0.24.6
$ react-native-scripts ios 
11:23:33: Starting packager...
***ERROR STARTING PACKAGER***

Error: You are using npm version 5.0.3. We recommend version 4.6.1. To install it, run 'npm i -g npm@4.6.1'.
11:23:41: Starting simulator...
```

**Comment by ASrima** [comment] 2018-04-08 00:59
Use this command (  npm install -g npm@latest ) and the problem should be solved as it will install the latest version of npm.
