### ISSUE TITLE
project create error

### ISSUE THREAD

**Issue by Amnok** [react-community/create-react-native-app#78] opened 2017-03-16 15:47 UTC
error D:\create-react-native-app\my-app2\node_modules\ref: Command failed.
Exit code: 1
Command: C:\Windows\system32\cmd.exe
Arguments: /d /s /c node-gyp rebuild
Directory: D:\create-react-native-app\my-app2\node_modules\ref
Output:
D:\create-react-native-app\my-app2\node_modules\ref>if not defined npm_config_node_gyp (node "C:\Users\AS00475240\AppData\Roaming\npm\node_modules\yarn\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node  rebuild )
gyp info it worked if it ends with ok
gyp info using node-gyp@3.5.0
gyp info using node@6.9.4 | win32 | x64
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at Object.failNoPython (C:\Users\AS00475240\AppData\Roaming\npm\node_modules\yarn\node_modules\node-gyp\lib\configure.js:454:19)
gyp ERR! stack     at Object.<anonymous> (C:\Users\AS00475240\AppData\Roaming\npm\node_modules\yarn\node_modules\node-gyp\lib\configure.js:480:16)
gyp ERR! stack     at C:\Users\AS00475240\AppData\Roaming\npm\node_modules\yarn\node_modules\graceful-fs\polyfills.js:284:29
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:123:15)
gyp ERR! System Windows_NT 10.0.10586
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\AS00475240\\AppData\\Roaming\\npm\\node_modules\\yarn\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd D:\create-react-native-app\my-app2\node_modules\ref
gyp ERR! node -v v6.9.4
gyp ERR! node-gyp -v v3.5.0
gyp ERR! not ok
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
`yarnpkg add --dev --exact --ignore-optional react-native-scripts` failed

**Comment by dikaiosune** [comment] 2017-03-16 16:17
Duplicate of #48 - I should be releasing a fix for this later today.

**Closed by dikaiosune** 2017-03-16 16:17 UTC

**Comment by Amnok** [comment] 2017-03-16 17:42
do notify when fix available
