### ISSUE TITLE
AwesomeProject@0.1.0 start: `react-native-scripts start`- ERR! Exit status 1

### ISSUE THREAD

**Issue by ExtAnimal** [react-community/create-react-native-app#382] opened 2017-08-26 10:35 UTC
##  npm start fails

Go through the few steps at https://facebook.github.io/react-native/docs/getting-started.html

type `npm start`

And get this:

```
> AwesomeProject@0.1.0 start /Users/nige/react-native/AwesomeProject
> react-native-scripts start

12:23:22 PM: Unable to start server
See https://git.io/v5vcn for more information, either install watchman or run the following snippet:
  sudo sysctl -w kern.maxfiles=5242880
  sudo sysctl -w kern.maxfilesperproc=524288
        

npm ERR! Darwin 16.6.0
npm ERR! argv "/Users/nige/.nvm/versions/node/v7.10.1/bin/node" "/Users/nige/.nvm/versions/node/v7.10.1/bin/npm" "start"
npm ERR! node v7.10.1
npm ERR! npm  v4.2.0
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! AwesomeProject@0.1.0 start: `react-native-scripts start`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the AwesomeProject@0.1.0 start script 'react-native-scripts start'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the AwesomeProject package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     react-native-scripts start
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs AwesomeProject
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls AwesomeProject
npm ERR! There is likely additional logging output above.
```

Here's the log file:
```
0 info it worked if it ends with ok
1 verbose cli [ '/Users/nige/.nvm/versions/node/v7.10.1/bin/node',
1 verbose cli   '/Users/nige/.nvm/versions/node/v7.10.1/bin/npm',
1 verbose cli   'start' ]
2 info using npm@4.2.0
3 info using node@v7.10.1
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle AwesomeProject@0.1.0~prestart: AwesomeProject@0.1.0
6 silly lifecycle AwesomeProject@0.1.0~prestart: no script for prestart, continuing
7 info lifecycle AwesomeProject@0.1.0~start: AwesomeProject@0.1.0
8 verbose lifecycle AwesomeProject@0.1.0~start: unsafe-perm in lifecycle true
9 verbose lifecycle AwesomeProject@0.1.0~start: PATH: /Users/nige/.nvm/versions/node/v7.10.1/lib/node_modules/npm/bin/node-gyp-bin:/Users/nige/react-native/AwesomeProject/node_modules/.bin:/Users/nige/.nvm/versions/node/v7.10.1/bin:/Users/nige/bin/Sencha/Cmd/6.1.2.5/..:/Users/nige/bin/Sencha/Cmd/6.1.1.76/..:/Users/nige/bin/Sencha/Cmd/6.0.3.34/..:/Users/nige/bin/Sencha/Cmd/6.0.3.34/..:/Users/nige/bin/Sencha/Cmd/6.0.2.8/..:/Users/nige/bin/Sencha/Cmd/6.0.2.8/..:/Users/nige/bin/Sencha/Cmd/6.0.1.75/..:/Users/nige/bin/Sencha/Cmd/6.0.1.64/..:/Users/nige/bin/Sencha/Cmd:/Users/nige/bin/Sencha/Cmd:/Users/nige/bin/Sencha/Cmd:/Users/nige/bin/Sencha/Cmd:/Users/nige/bin/Sencha/Cmd:/Users/nige/bin/Sencha/Cmd:/Users/nige/bin/Sencha/Cmd:/Users/nige/bin/Sencha/Cmd:/Users/nige/bin/Sencha/Cmd:/Users/nige/bin/Sencha/Cmd/6.0.0.122:/Users/nige/bin/Sencha/Cmd/6.0.0.119:/Users/nige/bin/Sencha/Cmd/6.0.0.117:/Users/nige/bin/Sencha/Cmd/6.0.0.101:/Users/nige/bin/Sencha/Cmd/6.0.0.99:/Users/nige/bin/Sencha/Cmd/6.0.0.81:/Users/nige/bin/Sencha/Cmd/6.0.0.50:/Users/nige/bin/Sencha/Cmd/6.0.0.46:/Users/nige/bin/Sencha/Cmd/6.0.0.45:/Users/nige/bin/Sencha/Cmd/6.0.0.42:/Users/nige/bin/Sencha/Cmd/5.5.0.31:/Users/nige/bin/Sencha/Cmd/5.5.0.16:/Users/nige/bin/Sencha/Cmd/5.1.1.38:/Users/nige/bin/Sencha/Cmd/5.1.0.26:/Users/nige/bin/Sencha/Cmd/5.1.0.25:/Users/nige/bin/Sencha/Cmd/5.1.0.20:/Users/nige/bin/Sencha/Cmd/5.1.0.21:/Users/nige/bin/Sencha/Cmd/5.1.0.13:/Users/nige/bin/Sencha/Cmd/5.1.0.11:/Users/nige/bin/Sencha/Cmd/5.1.0.6:/Users/nige/bin/Sencha/Cmd/5.0.3.324:/Users/nige/bin/Sencha/Cmd/5.0.3.317:/Users/nige/bin/Sencha/Cmd/5.0.1.224:/Users/nige/bin/Sencha/Cmd/5.0.1.219:/Users/nige/bin/Sencha/Cmd/5.0.1.214:/Users/nige/bin/Sencha/Cmd/5.0.1.211:/Users/nige/bin/Sencha/Cmd/6.2.0.46/..:/Users/nige/bin/Sencha/Cmd/6.2.0.36/..:/Users/nige/bin/Sencha/Cmd/6.2.0.22/..:/Users/nige/bin/Sencha/Cmd/6.2.0.14/..:/Users/nige/bin/Sencha/Cmd/6.2.0.4/..:/Users/nige/bin/Sencha/Cmd/6.1.3.16/..:/Users/nige/bin/Sencha/Cmd/6.0.0.122:/Users/nige/bin/Sencha/Cmd/6.0.0.119:/Users/nige/bin/Sencha/Cmd/6.0.0.117:/Users/nige/bin/Sencha/Cmd/6.0.0.101:/Users/nige/bin/Sencha/Cmd/6.0.0.99:/Users/nige/bin/Sencha/Cmd/6.0.0.81:/Users/nige/bin/Sencha/Cmd/6.0.0.50:/Users/nige/bin/Sencha/Cmd/6.0.0.46:/Users/nige/bin/Sencha/Cmd/6.0.0.45:/Users/nige/bin/Sencha/Cmd/6.0.0.42:/Users/nige/bin/Sencha/Cmd/5.5.0.31:/Users/nige/bin/Sencha/Cmd/5.5.0.16:/Users/nige/bin/Sencha/Cmd/5.1.1.38:/Users/nige/bin/Sencha/Cmd/5.1.0.26:/Users/nige/bin/Sencha/Cmd/5.1.0.25:/Users/nige/bin/Sencha/Cmd/5.1.0.20:/Users/nige/bin/Sencha/Cmd/5.1.0.21:/Users/nige/bin/Sencha/Cmd/5.1.0.13:/Users/nige/bin/Sencha/Cmd/5.1.0.11:/Users/nige/bin/Sencha/Cmd/5.1.0.6:/Users/nige/bin/Sencha/Cmd/5.0.3.324:/Users/nige/bin/Sencha/Cmd/5.0.3.317:/Users/nige/bin/Sencha/Cmd/5.0.1.224:/Users/nige/bin/Sencha/Cmd/5.0.1.219:/Users/nige/bin/Sencha/Cmd/5.0.1.214:/Users/nige/bin/Sencha/Cmd/5.0.1.211:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/git/bin
10 verbose lifecycle AwesomeProject@0.1.0~start: CWD: /Users/nige/react-native/AwesomeProject
11 silly lifecycle AwesomeProject@0.1.0~start: Args: [ '-c', 'react-native-scripts start' ]
12 silly lifecycle AwesomeProject@0.1.0~start: Returned: code: 1  signal: null
13 info lifecycle AwesomeProject@0.1.0~start: Failed to exec start script
14 verbose stack Error: AwesomeProject@0.1.0 start: `react-native-scripts start`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/Users/nige/.nvm/versions/node/v7.10.1/lib/node_modules/npm/lib/utils/lifecycle.js:279:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:194:7)
14 verbose stack     at ChildProcess.<anonymous> (/Users/nige/.nvm/versions/node/v7.10.1/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:194:7)
14 verbose stack     at maybeClose (internal/child_process.js:899:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid AwesomeProject@0.1.0
16 verbose cwd /Users/nige/react-native/AwesomeProject
17 error Darwin 16.6.0
18 error argv "/Users/nige/.nvm/versions/node/v7.10.1/bin/node" "/Users/nige/.nvm/versions/node/v7.10.1/bin/npm" "start"
19 error node v7.10.1
20 error npm  v4.2.0
21 error code ELIFECYCLE
22 error errno 1
23 error AwesomeProject@0.1.0 start: `react-native-scripts start`
23 error Exit status 1
24 error Failed at the AwesomeProject@0.1.0 start script 'react-native-scripts start'.
24 error Make sure you have the latest version of node.js and npm installed.
24 error If you do, this is most likely a problem with the AwesomeProject package,
24 error not with npm itself.
24 error Tell the author that this fails on your system:
24 error     react-native-scripts start
24 error You can get information on how to open an issue for this project with:
24 error     npm bugs AwesomeProject
24 error Or if that isn't available, you can get their info via:
24 error     npm owner ls AwesomeProject
24 error There is likely additional logging output above.
25 verbose exit [ 1, true ]
```

**Comment by ramalheiro** [comment] 2017-08-26 16:48
Same error here

**Comment by ajaxon** [comment] 2017-08-26 22:46
I'm getting the same error

**Comment by megane42** [comment] 2017-08-27 07:27
As suggested at the error message, [installing watchman](https://facebook.github.io/watchman/docs/install.html) solved this error for me (OSX 10.9.5). It seems like that the necessity of watchman should be mentioned in README.

In addition, you may have to `touch .watchmanconfig` and `git init` on your project's root to solve the following error:

```
jest-haste-map: Watchman crawl failed. Retrying once with node crawler.
  Usually this happens when watchman isn't running. Create an empty `.watchmanconfig` file in your project's root folder or initialize a git or hg repository in your project.
  Error: Watchman error: query failed: synchronization failed: No such file or directory. Make sure watchman is running for this project. See https://facebook.github.io/watchman/docs/troubleshooting.html.
```

**Comment by hect1995** [comment] 2017-08-27 08:10
When I installed it from source, and I execute `MacBook-Pro-de-Hector:watchman Hector$ ./autogen.sh` this error appears: `./autogen.sh: line 9: aclocal: command not found /br
./autogen.sh: line 10: autoheader: command not found
./autogen.sh: line 11: automake: command not found
./autogen.sh: line 12: autoconf: command not found`

**Comment by hect1995** [comment] 2017-08-27 08:26
Doing the stepts in #229 I got this error:
`MacBook-Pro-de-Hector:local Hector$ create-react-native-app FirstProject
(node:834) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: EACCES: permission denied, mkdir '/usr/local/FirstProject'`

**Comment by chetkhatri** [comment] 2017-08-31 22:23
Downgrade the npm version 5 to 4 by command npm install -g npm@4.6.1 and it works

**Comment by simplyluke** [comment] 2017-09-06 05:46
Watchman was the solution for me as well.

**Comment by chetankhatri** [comment] 2017-09-06 05:53
@ExtAnimal @simplyluke Can we close this issue, if solution is looks relevant to you.

**Comment by sjmcculloch** [comment] 2017-09-11 06:40
Watchman worked for me

**Comment by ashwanth1109** [comment] 2017-09-28 07:04
I had the same error. So, the terminal mentions either to install watchman or type in the following code:

sudo sysctl -w kern.maxfiles=5242880
sudo sysctl -w kern.maxfilesperproc=524288

I tried the code and it worked. Looking at the other replies, I'm guessing watchman also works, but to me typing two lines of code seemed like the easier option.

**Comment by devWebNuts** [comment] 2017-10-02 05:14
I applied the same solution as @ashwanth1109 as it's all good now. Cheers

**Comment by dikaiosune** [comment] 2017-10-06 22:27
Seems like the watchman resolution has worked for lots of people here.

**Closed by dikaiosune** 2017-10-06 22:27 UTC

**Comment by codetoon** [comment] 2017-10-08 12:28
@ashwanth1109 works for me without installing watchman.

**Comment by arun-kambhammettu** [comment] 2017-11-08 19:50
downgrading to 4 and adding these two lines worked for me.

sudo sysctl -w kern.maxfiles=5242880
sudo sysctl -w kern.maxfilesperproc=524288

Thanks @ashwanth1109

**Comment by xuxx1018** [comment] 2017-11-09 21:24
Problem fixed by installing watchman:
brew install watchman

**Comment by dustturtle** [comment] 2017-11-23 11:37
sudo sysctl -w kern.maxfiles=5242880
sudo sysctl -w kern.maxfilesperproc=524288
worked for me!

**Comment by eshwarenm** [comment] 2017-11-25 11:18
sudo sysctl -w kern.maxfiles=5242880
sudo sysctl -w kern.maxfilesperproc=524288
worked for me!

**Comment by tuanluu-agilityio** [comment] 2017-11-28 09:02
https://github.com/react-community/create-react-native-app/issues/382#issuecomment-325181957 
[installing watchman](https://facebook.github.io/watchman/docs/install.html) resolved my issue. 
Thanks @megane42

**Comment by hahahatrick** [comment] 2017-12-13 08:38
@megane42  Can you tell me how you installed watchman on OSX 10.9.5? Brew supports only >= Yosemite and I'm unable to build from source because 'fstatat' is not available on OSX.

**Comment by megane42** [comment] 2017-12-13 16:08
@hahahatrick My .bash_history says:

```
git clone https://github.com/facebook/watchman.git
cd watchman/
git checkout v4.7.0
./autogen.sh
./configure
make
sudo make install
watchman --version
```

but I have already upgraded to OSX 10.12 so I can't confirm...
Hope this helps you.

**Comment by zoheiry** [comment] 2017-12-15 10:27
Just installing watchman worked for me **OSX 10.12.6**
```
brew update
brew install watchman
```
Thanks @megane42

**Comment by razi1122** [comment] 2017-12-25 07:23
Just installing watchman is work for me to ubuntu 16.04

**Comment by grab-a** [comment] 2018-01-26 17:03
This **worked** for me and is **faster than** installing **watchman**!

sudo sysctl -w kern.maxfiles=5242880
sudo sysctl -w kern.maxfilesperproc=524288

**Comment by ctp-placebo** [comment] 2018-02-03 13:17
$ npm install watchman
npm WARN deprecated watchman@1.0.0: Package no longer supported. Contact support@npmjs.com for more info.
tipcalc@0.1.0 /Users/name/Developments/LUT/tipcalc
└── watchman@1.0.0 

Maybe npm wasn't the way to do it and is getting an old version because npm is put of date? I had to downgrade npm to 4.x.x from 5.xx because otherwise else the react-native/ios simulator would not work.   

It's like no-one is talking to anyone else and allowing upstream/downstream to make changes before versions are pushed.

**Comment by ide** [comment] 2018-02-05 19:42
See the Watchman installation docs for how to install Watchman, which depends on the OS you are using: https://facebook.github.io/watchman/docs/install.html. For macOS, you can install Homebrew and run `brew install watchman`. It's also a good idea to increase the inotify limits (also OS-dependent) and the Watchman site has troubleshooting info here: https://facebook.github.io/watchman/docs/troubleshooting.html.

**Comment by Pravin-Parkhi** [comment] 2018-02-22 21:15
Running below two commands resolved my issue.

```
sudo sysctl -w kern.maxfiles=5242880
sudo sysctl -w kern.maxfilesperproc=524288
```

**Comment by sagar-hike** [comment] 2018-03-08 04:58
```
sudo sysctl -w kern.maxfiles=5242880
sudo sysctl -w kern.maxfilesperproc=524288
```
worked for me.

**Comment by ImArtur** [comment] 2018-03-12 10:05
The problem is back, but @ashwanth1109  solution work!

**Comment by priyankamalviya** [comment] 2018-03-14 04:47
I first started with npm but I had 5.6.0 and downgrading did not help. I restarted my installation, the yarn way, and then  downloaded watchman: brew install watchman. Worked like a charm! :)

**Comment by swabzz** [comment] 2018-03-17 11:33
sudo sysctl -w kern.maxfiles=5242880
sudo sysctl -w kern.maxfilesperproc=524288
worked for me!

**Comment by jhon312020** [comment] 2018-03-20 08:47
For me npm start, but when I try to view the application via android mobile it just shows exp symbol and it is not loading the app.  It works with ios simulator.

**Comment by woei66** [comment] 2018-04-24 12:44
I had the same error and what I did is "npm install" to install all dependency and it works.

**Comment by aleczadikian** [comment] 2018-04-26 19:46
Why are we supposed to change the kernel max files parameters to fix this? That's not something you change without thinking about it.

**Comment by dilipkosuri** [comment] 2018-05-09 05:28
Both the solutions would work as suggested above:
1) Update brew and install watchman
2) Increase the processing kernel files size

**Comment by jiovanniro** [comment] 2018-05-15 05:25
Watchman is now deprecated. 
https://www.npmjs.com/package/watchman

The solution is to run the two commands: 
```
  sudo sysctl -w kern.maxfiles=5242880
  sudo sysctl -w kern.maxfilesperproc=524288
```

**Comment by eroncastro** [comment] 2018-06-03 15:49
I just had to install watchman using brew and it worked for me!

**Comment by masudiiuc** [comment] 2018-06-12 21:21
Watchman was the solution for me as well.

**Comment by mattegalli** [comment] 2018-06-19 02:38
Only on OS 10.6 and earlier you should increase the pre-process descriptor limit.
__To do it temporary__ you can just type in your terminal the following:

$ sudo sysctl -w kern.maxfiles=10485760
$ sudo sysctl -w kern.maxfilesperproc=1048576

Otherwise, if you'd like to __keep them always__, modify */etc/sysctl.conf* with these new values:

kern.maxfiles=10485760
kern.maxfilesperproc=1048576

**Comment by Naresh6885** [comment] 2018-07-19 04:49
Run the following commands, copy from your terminal. It works for me well.

sudo sysctl -w kern.maxfiles=5242880
sudo sysctl -w kern.maxfilesperproc=524288

**Comment by danielricecodes** [comment] 2018-08-25 14:36
How on earth is anyone supposed to figure this out on their own without Google.  The error thats related to this is nonsense!  

FWIW, In the Ruby community, if a dependency is missing we actually tell you about it instead of letting the thread go splat.  Something along the lines of "`watchman` could not be found.  Please run `brew install watchman` and try again".  JavaScript community...you all have so much to learn still.

**Comment by moonbury** [comment] 2018-09-17 05:52
> sudo sysctl -w kern.maxfiles=5242880
> sudo sysctl -w kern.maxfilesperproc=524288
> worked for me!

This worked for me.
