### ISSUE TITLE
cant create app in windows 10

### ISSUE THREAD

**Issue by dansha** [react-community/create-react-native-app#66] opened 2017-03-14 18:05 UTC
create-react-native-app was installed without errors but when I try to create a new app i get:

```
C:\dev\rn>create-react-native-app testcrna
Creating a new React Native app in C:\dev\rn\testcrna.

Installing packages. This might take a couple minutes.
Installing react-native-scripts...

yarn add v0.18.0
info No lockfile found.
[1/4] Resolving packages...
warning react-native-scripts > xdl > node-uuid@1.4.7: use uuid module instead
warning react-native-scripts > xdl > @exponent/ngrok > node-uuid@1.4.7: use uuid module instead
warning react-native-scripts > xdl > auth0-js > xtend > object-keys@0.4.0:
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
[1/5] ⠐ @exponent/ngrok
[-/5] ⠐ waiting...
[3/5] ⠐ ref: gyp info spawn args   '-Goutput_dir=.' ]
[4/5] ⠐ runas: spawn args   '-Goutput_dir=.' ]
error Error running install script for optional dependency: "C:\\dev\\rn\\testcrna\\node_modules\\runas: Command failed.\nExit code: 1\nCommand: C:\\WINDOWS\\system32\\cmd.exe\nArguments: /d /s /c node-gyp rebuild\nDirectory: C:\\dev\\rn\\testcrna\\node_modules\\runas\nOutput:\nC:\\dev\\rn\\testcrna\\node_modules\\runas>if not defined npm_config_node_gyp (node \"C:\\Users\\shami\\AppData\\Roaming\\npm\\node_modules\\yarn\\bin\\node-gyp-bin\\\\..\\..\\node_modules\\node-gyp\\bin\\node-gyp.js\" rebuild )  else (node  rebuild ) \r\ngyp info it worked if it ends with ok\ngyp info using node-gyp@3.4.0\ngyp info using node@6.10.0 | win32 | x64\ngyp info spawn C:\\Python27\\python.exe\ngyp info spawn args [ 'C:\\\\Users\\\\shami\\\\AppData\\\\Roaming\\\\npm\\\\node_modules\\\\yarn\\\\node_modules\\\\node-gyp\\\\gyp\\\\gyp_main.py',\ngyp info spawn args   'binding.gyp',\ngyp info spawn args   '-f',\ngyp info spawn args   'msvs',\ngyp info spawn args   '-G',\ngyp info spawn args   'msvs_version=auto',\ngyp info spawn args   '-I',\ngyp info spawn args   'C:\\\\dev\\\\rn\\\\testcrna\\\\node_modules\\\\runas\\\\build\\\\config.gypi',\ngyp info spawn args   '-I',\ngyp info spawn args   'C:\\\\Users\\\\shami\\\\AppData\\\\Roaming\\\\npm\\\\node_modules\\\\yarn\\\\node_modules\\\\node-gyp\\\\addon.gypi',\ngyp info spawn args   '-I',\ngyp info spawn args   'C:\\\\Users\\\\shami\\\\.node-gyp\\\\6.10.0\\\\include\\\\node\\\\common.gypi',\ngyp info spawn args   '-Dlibrary=shared_library',\ngyp info spawn args   '-Dvisibility=default',\ngyp info spawn args   '-Dnode_root_dir=C:\\\\Users\\\\shami\\\\.node-gyp\\\\6.10.0',\ngyp info spawn args   '-Dnode_gyp_dir=C:\\\\Users\\\\shami\\\\AppData\\\\Roaming\\\\npm\\\\node_modules\\\\yarn\\\\node_modules\\\\node-gyp',\ngyp info spawn args   '-Dnode_lib_file=node.lib',\ngyp info spawn args   '-Dmodule_root_dir=C:\\\\dev\\\\rn\\\\testcrna\\\\node_modules\\\\runas',\ngyp info spawn args   '--depth=.',\ngyp info spawn args   '--no-parallel',\ngyp info spawn args   '--generator-output',\ngyp info spawn args   'C:\\\\dev\\\\rn\\\\testcrna\\\\node_modules\\\\runas\\\\build',\ngyp info spawn args   '-Goutput_dir=.' ]\nTraceback (most recent call last):\r\n  File \"C:\\Users\\shami\\AppData\\Roaming\\npm\\node_modules\\yarn\\node_modules\\node-gyp\\gyp\\gyp_main.py\", line 16, in <module>\r\n    sys.exit(gyp.script_main())\r\n  File \"C:\\Users\\shami\\AppData\\Roaming\\npm\\node_modules\\yarn\\node_modules\\node-gyp\\gyp\\pylib\\gyp\\__init__.py\", line 545, in script_main\r\n    return main(sys.argv[1:])\r\n  File \"C:\\Users\\shami\\AppData\\Roaming\\npm\\node_modules\\yarn\\node_modules\\node-gyp\\gyp\\pylib\\gyp\\__init__.py\", line 538, in main\r\n    return gyp_main(args)\r\n  File \"C:\\Users\\shami\\AppData\\Roaming\\npm\\node_modules\\yarn\\node_modules\\node-gyp\\gyp\\pylib\\gyp\\__init__.py\", line 514, in gyp_main\r\n    options.duplicate_basename_check)\r\n  File \"C:\\Users\\shami\\AppData\\Roaming\\npm\\node_modules\\yarn\\node_modules\\node-gyp\\gyp\\pylib\\gyp\\__init__.py\", line 130, in Load\r\n    params['parallel'], params['root_targets'])\r\n  File \"C:\\Users\\shami\\AppData\\Roaming\\npm\\node_modules\\yarn\\node_modules\\node-gyp\\gyp\\pylib\\gyp\\input.py\", line 2775, in Load\r\n    variables, includes, depth, check, True)\r\n  File \"C:\\Users\\shami\\AppData\\Roaming\\npm\\node_modules\\yarn\\node_modules\\node-gyp\\gyp\\pylib\\gyp\\input.py\", line 417, in LoadTargetBuildFile\r\n    build_file_data, PHASE_EARLY, variables, build_file_path)\r\n  File \"C:\\Users\\shami\\AppData\\Roaming\\npm\\node_modules\\yarn\\node_modules\\node-gyp\\gyp\\pylib\\gyp\\input.py\", line 1214, in ProcessVariablesAndConditionsInDict\r\n    variables, build_file, 'variables')\r\n  File \"C:\\Users\\shami\\AppData\\Roaming\\npm\\node_modules\\yarn\\node_modules\\node-gyp\\gyp\\pylib\\gyp\\input.py\", line 1225, in ProcessVariablesAndConditionsInDict\r\n    'only, found ' + expanded.__class__.__name__ + ' for ' + key)\r\nValueError: Variable expansion in this context permits str and int only, found long for lastUpdateCheck while trying to load binding.gyp\r\ngyp ERR! configure error \ngyp ERR! stack Error: `gyp` failed with exit code: 1\ngyp ERR! stack     at ChildProcess.onCpExit (C:\\Users\\shami\\AppData\\Roaming\\npm\\node_modules\\yarn\\node_modules\\node-gyp\\lib\\configure.js:305:16)\ngyp ERR! stack     at emitTwo (events.js:106:13)\ngyp ERR! stack     at ChildProcess.emit (events.js:191:7)\ngyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)\ngyp ERR! System Windows_NT 10.0.14393\ngyp ERR! command \"C:\\\\Program Files\\\\no[1/5] ⠈ @exponent/ngrok
[-/5] ⠈ waiting...
[3/5] ⠈ ref: not ok
[-/5] ⠈ waiting...
error C:\dev\rn\testcrna\node_modules\ref: Command failed.
Exit code: 1
Command: C:\WINDOWS\system32\cmd.exe
Arguments: /d /s /c node-gyp rebuild
Directory: C:\dev\rn\testcrna\node_modules\ref
Output:
C:\dev\rn\testcrna\node_modules\ref>if not defined npm_config_node_gyp (node "C:\Users\shami\AppData\Roaming\npm\node_modules\yarn\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node  rebuild )
gyp info it worked if it ends with ok
gyp info using node-gyp@3.4.0
gyp info using node@6.10.0 | win32 | x64
gyp info spawn C:\Python27\python.exe
gyp info spawn args [ 'C:\\Users\\shami\\AppData\\Roaming\\npm\\node_modules\\yarn\\node_modules\\node-gyp\\gyp\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-G',
gyp info spawn args   'msvs_version=auto',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\dev\\rn\\testcrna\\node_modules\\ref\\build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\shami\\AppData\\Roaming\\npm\\node_modules\\yarn\\node_modules\\node-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\shami\\.node-gyp\\6.10.0\\include\\node\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\Users\\shami\\.node-gyp\\6.10.0',
gyp info spawn args   '-Dnode_gyp_dir=C:\\Users\\shami\\AppData\\Roaming\\npm\\node_modules\\yarn\\node_modules\\node-gyp',
gyp info spawn args   '-Dnode_lib_file=node.lib',
gyp info spawn args   '-Dmodule_root_dir=C:\\dev\\rn\\testcrna\\node_modules\\ref',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'C:\\dev\\rn\\testcrna\\node_modules\\ref\\build',
gyp info spawn args   '-Goutput_dir=.' ]
Traceback (most recent call last):
  File "C:\Users\shami\AppData\Roaming\npm\node_modules\yarn\node_modules\node-gyp\gyp\gyp_main.py", line 16, in <module>
    sys.exit(gyp.script_main())
  File "C:\Users\shami\AppData\Roaming\npm\node_modules\yarn\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 545, in script_main
    return main(sys.argv[1:])
  File "C:\Users\shami\AppData\Roaming\npm\node_modules\yarn\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 538, in main
    return gyp_main(args)
  File "C:\Users\shami\AppData\Roaming\npm\node_modules\yarn\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 514, in gyp_main
    options.duplicate_basename_check)
  File "C:\Users\shami\AppData\Roaming\npm\node_modules\yarn\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 130, in Load
    params['parallel'], params['root_targets'])
  File "C:\Users\shami\AppData\Roaming\npm\node_modules\yarn\node_modules\node-gyp\gyp\pylib\gyp\input.py", line 2775, in Load
    variables, includes, depth, check, True)
  File "C:\Users\shami\AppData\Roaming\npm\node_modules\yarn\node_modules\node-gyp\gyp\pylib\gyp\input.py", line 417, in LoadTargetBuildFile
    build_file_data, PHASE_EARLY, variables, build_file_path)
  File "C:\Users\shami\AppData\Roaming\npm\node_modules\yarn\node_modules\node-gyp\gyp\pylib\gyp\input.py", line 1214, in ProcessVariablesAndConditionsInDict
    variables, build_file, 'variables')
  File "C:\Users\shami\AppData\Roaming\npm\node_modules\yarn\node_modules\node-gyp\gyp\pylib\gyp\input.py", line 1225, in ProcessVariablesAndConditionsInDict
    'only, found ' + expanded.__class__.__name__ + ' for ' + key)
ValueError: Variable expansion in this context permits str and int only, found long for lastUpdateCheck while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (C:\Users\shami\AppData\Roaming\npm\node_modules\yarn\node_modules\node-gyp\lib\configure.js:305:16)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Windows_NT 10.0.14393
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\shami\\AppData\\Roaming\\npm\\node_modules\\yarn\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\dev\rn\testcrna\node_modules\ref
gyp ERR! node -v v6.10.0
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
`yarnpkg add --dev --exact react-native-scripts` failed

```

**Comment by dikaiosune** [comment] 2017-03-14 18:24
Hi! Thanks for the report! This appears to be a duplicate of the node-gyp error reported in #48. I am working on fixing this problem, but the short term workaround is to force CRNA to use npm by uninstalling yarn (not an awesome fix, I know ☹️ ). I hope to have a release later today which resolves this.

**Closed by dikaiosune** 2017-03-14 18:24 UTC
