### ISSUE TITLE
Expo app on iphone doesn't see server.

### ISSUE THREAD

**Issue by mich4s** [react-community/create-react-native-app#174] opened 2017-04-20 21:37 UTC
I'm using windows 10 and iphone 5s(if that matter) to test expo app. Both systems are connected to same router(i can ping iphone from windows), but when i scan qr i get "Error while loading: The request timed out." (code -1001).

Is there anything more i have to do with network settings to reach my expo server from phone?

**Comment by dikaiosune** [comment] 2017-04-20 22:08
Hi! Sorry to hear that you are having issues with your network configuration. Unfortunately due to time constraints I'm going to be closing issues on this repo which do not use the issue template and have not confirmed following the network troubleshooting section of the user guide. I would recommend starting there, and maybe also try installing [XDE](https://docs.expo.io/versions/v16.0.0/introduction/installation.html) which is able to bypass some networking issues for you.

**Closed by dikaiosune** 2017-04-20 22:08 UTC
Labels: missing-template

**Comment by JorgeMadson** [comment] 2017-10-19 03:41
Thanks @dikaiosune , installing the XDE resolved the problem.

**Comment by beltrancaliz** [comment] 2018-04-12 01:16
Same issue here, used to work like a charm with the Expo XDE Windows client using a tunnel but now it does not even work via LAN or localhost
