### ISSUE TITLE
npm start hangs on - "Starting packager..."

### ISSUE THREAD

**Issue by WeslleyNasRocha** [react-community/create-react-native-app#439] opened 2017-10-16 17:21 UTC
## Description

When i run `yarn start` it get stuck with a messagem `Starting packager...`

## Expected Behavior

Run `yarn start` and the packager starts

## Observed Behavior

The packager hangs indefinitely

```
C:\Users\weslley.rocha\Documents\Projects\React-native\expo\swype3>yarn start
yarn run v1.1.0
$ react-native-scripts start
15:08:32: Starting packager...
15:20:37: Stopping packager...
15:20:37: Packager stopped.
Done in 725.66s.
```

## Environment

Please run these commands in the project folder and fill in their results:

* `npm ls react-native-scripts`: 

> swype3@0.1.0 C:\Users\weslley.rocha\Documents\Projects\React-native\expo\swype3
`-- react-native-scripts@1.5.0

* `npm ls react-native`:

> swype3@0.1.0 C:\Users\weslley.rocha\Documents\Projects\React-native\expo\swype3
`-- react-native@0.48.4

* `npm ls expo`:

> swype3@0.1.0 C:\Users\weslley.rocha\Documents\Projects\React-native\expo\swype3
`-- expo@21.0.2

* `node -v`:

> v8.2.1

* `npm -v`:

> 4.6.1

* `yarn --version`:

> 1.1.0

* `watchman version`:

> 'watchman' não é reconhecido como um comando interno
ou externo, um programa operável ou um arquivo em lotes.

Also specify:

1. Operating system: Windows 7 x64
2. Phone/emulator/simulator & version: Genymotion

**Comment by WeslleyNasRocha** [comment] 2017-10-16 17:22
If i run `react-native start` it goes:
```
Scanning 768 folders for symlinks in C:\Users\weslley.rocha\Documents\Projects\React-native\expo\swype3\node_modul
es (18ms)
 ┌────────────────────────────────────────────────────────────────────────────┐
 │  Running packager on port 8081.                                            │
 │                                                                            │
 │  Keep this packager running while developing on any JS projects. Feel      │
 │  free to close this tab and run your own packager instance if you          │
 │  prefer.                                                                   │
 │                                                                            │
 │  https://github.com/facebook/react-native                                  │
 │                                                                            │
 └────────────────────────────────────────────────────────────────────────────┘
Looking for JS files in
   C:\Users\weslley.rocha\Documents\Projects\React-native\expo\swype3


React packager ready.

Loading dependency graph...
```

**Comment by HigoOliveira** [comment] 2017-10-17 11:26
Hi, I solved this problem by looking at this page: [https://github.com/facebook/react-native/issues/10188#issuecomment-251677161](url).

by Google Tradutor ;D

**Comment by WernerRaath** [comment] 2017-10-24 08:59
@HigoOliveira, unfortunately the link that you provided does not exist anymore.

**Comment by dhruvdutt** [comment] 2017-10-25 07:37
Duplicate of #343 

You can try this:

```bash
echo 999999 | sudo tee -a /proc/sys/fs/inotify/max_user_watches && echo 999999 | sudo tee -a /proc/sys/fs/inotify/max_queued_events && echo 999999 | sudo tee -a /proc/sys/fs/inotify/max_user_instances && echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p
```

If it's still stuck, then install watchman from [here](https://facebook.github.io/watchman/docs/install.html) and do this
```bash
watchman watch-del-all && watchman shutdown-server
```

**Closed** 2018-01-19 22:22 UTC

**Comment by borch84** [comment] 2018-06-30 04:51
Hi I am getting the same problem. I created a test app, I was able to work with it using Expo, but now when I run npm start it gets stuck at "Starting  Packager..."
react-native info returns this:

Environment:
  OS: macOS High Sierra 10.13.5
  Node: 8.11.3
  Yarn: 1.7.0
  npm: 6.1.0
  Watchman: 4.9.4
  Xcode: Not Found
  Android Studio: 3.0 AI-171.4443003

Packages: (wanted => installed)
  react: 16.0.0-alpha.12 => 16.0.0-alpha.12
  react-native: ^0.55.4 => 0.55.4

When I run npm start --verbose I got this output:

 sudo npm start --verbose
npm info it worked if it ends with ok
npm verb cli [ '/usr/local/bin/node',
npm verb cli   '/usr/local/bin/npm',
npm verb cli   'start',
npm verb cli   '--verbose' ]
npm info using npm@6.1.0
npm info using node@v8.11.3
npm verb run-script [ 'prestart', 'start', 'poststart' ]
npm info lifecycle aws-mobile-react-native-sample@0.1.0~prestart: aws-mobile-react-native-sample@0.1.0
npm info lifecycle aws-mobile-react-native-sample@0.1.0~start: aws-mobile-react-native-sample@0.1.0

> aws-mobile-react-native-sample@0.1.0 start /Users/borch/Documents/React_Native/pet-tracker
> react-native-scripts start

22:24:25: Starting packager...
***ERROR STARTING PACKAGER***
No issue with doctor-watchman-version
No issue with doctor-problem-checking-watchman-version
No issue with doctor-both-app-and-exp-json
No issue with doctor-schema-validation
No issue with doctor-validate-asset-fields
No issue with doctor-schema-validation-exception
No issue with doctor-unversioned
No issue with doctor-versions-endpoint-failed
No issue with doctor-invalid-sdk-version
No issue with doctor-node-modules-missing
No issue with doctor-react-native-not-installed
Starting Metro Bundler on port 19001.
Metro Bundler ready.

jest-haste-map: @providesModule naming collision:
  Duplicate module name: crud
  Paths: /Users/borch/Documents/React_Native/pet-tracker/awsmobilejs/backend/cloud-api/itemsHandler/package.json collides with /Users/borch/Documents/React_Native/pet-tracker/awsmobilejs/#current-backend-info/cloud-api/itemsHandler/package.json

This warning is caused by a @providesModule declaration with the same name across two different files.
22:28:52: Stopping packager...
22:28:52: Packager stopped.
npm verb lifecycle aws-mobile-react-native-sample@0.1.0~start: unsafe-perm in lifecycle true
npm verb lifecycle aws-mobile-react-native-sample@0.1.0~start: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/borch/Documents/React_Native/pet-tracker/node_modules/.bin:/Users/borch/Documents/platform-tools:/Library/Java/JavaVirtualMachines/jdk1.7.0_79.jdk/Contents/Home/bin:/usr/local/cuda/bin:/Users/borch/anaconda3/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/Users/borch/bin:/Users/borch/Documents/Robotica/esp/xtensa-esp32-elf/bin
npm verb lifecycle aws-mobile-react-native-sample@0.1.0~start: CWD: /Users/borch/Documents/React_Native/pet-tracker
npm info lifecycle aws-mobile-react-native-sample@0.1.0~poststart: aws-mobile-react-native-sample@0.1.0
npm verb exit [ 0, true ]
npm timing npm Completed in 267308ms
npm info ok 

From the previous output it says: ***ERROR STARTING PACKAGER*** but I can't find what else to look in order to discover the real cause.

I have already increase file number:

sysctl -a | grep kern.maxfiles
kern.maxfiles: 5242880
kern.maxfilesperproc: 524288

I updated watchman to 4.9.4.
