### ISSUE TITLE
Create-react-native-app Cannot read property 'find' of undefined

### ISSUE THREAD

**Issue by parmpreet** [react-community/create-react-native-app#136] opened 2017-03-29 06:30 UTC
## Description
I am getting error while starting the new app with 
npm start or npm run ios

## Expected Behavior

What action did you perform, and what did you expect to happen?
create-react-native-app nav-app
cd nav-app
npm start
## Observed Behavior

What actually happened when you performed the above actions?

<img width="371" alt="glass_and_iphone_6_ _ios_10_2__14c89_" src="https://cloud.githubusercontent.com/assets/4441356/24441254/5067e974-14b5-11e7-9bb9-0d1d81c2fe58.png">

If there's an error message, please paste the *full terminal output and error message* in this code block:

```
7:18:38 PM: (node:6449) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 685): SyntaxError: TransformError: /Users/parm/Documents/learning/expo/nav-app/node_modules/expo/src/Expo.js: /Users/parm/Documents/learning/expo/nav-app/node_modules/expo/src/Expo.js: Cannot read property 'find' of undefined

```

## Environment
react-native-scripts@0.0.26
react-native@0.42.3
expo@15.1.2
node v7.0.0
npm 4.4.1
watchman 4.7.0
macos 10.12.3
iphone 6 simulator (SimulatorApp-726.7)

**Comment by maxinminax** [comment] 2017-03-29 06:36
+1

**Comment by onurcankaya** [comment] 2017-03-29 07:31
+1

**Comment by gnuwilliam** [comment] 2017-03-29 08:02
I'm having the same issue

**Comment by kaiyuanlee** [comment] 2017-03-29 08:52
+1

**Comment by MarcinThinkApps** [comment] 2017-03-29 09:15
+1

**Comment by mmieszek** [comment] 2017-03-29 09:16
+1

**Comment by mrasoahaingo** [comment] 2017-03-29 12:10
+1

**Comment by iamfeek** [comment] 2017-03-29 12:13
+1

**Comment by paradigmist** [comment] 2017-03-29 12:30
+9

**Comment by vlexaargas** [comment] 2017-03-29 14:00
+1

**Comment by muraterd** [comment] 2017-03-29 14:47
+1

**Comment by dikaiosune** [comment] 2017-03-29 15:08
Hi! Thanks for the report. I'm looking into this now. If you're also experiencing this issue, please refrain from leaving '+1' comments.

**Comment by vikkio88** [comment] 2017-03-29 15:15
having the same issue with the same versions of all the packages, but on ubuntu and with the android simulator.

**Comment by dikaiosune** [comment] 2017-03-29 16:08
Hi everyone! It looks like there were a few upstream dependencies that changed in the last day or so (yay semver!) and I'm looking into which may be the source of the issue here.

**Comment by dikaiosune** [comment] 2017-03-29 16:27
I've identified the likely cause of the error (will file a report soon on the [open issue](https://github.com/tleunen/babel-plugin-module-resolver/issues/144)). Doing a little more testing and then I'll push out a release of CRNA.

**Comment by dikaiosune** [comment] 2017-03-29 17:22
This has been resolved, you should be able to create a new project and have it work again.

Since this affected so many people, here's a brief breakdown of what went wrong:

* [babel-plugin-module-resolver](https://github.com/tleunen/babel-plugin-module-resolver) released 2.6.0 last night.
* [babel-preset-expo](https://www.npmjs.com/package/babel-preset-expo), which is a dependency of the [Expo SDK](https://github.com/expo/exponent-sdk) and is used in CRNA to transform local asset `require`s for the client app, depended on `"babel-plugin-module-resolver": "^2.3.0"`, which allowed the new 2.6.0 version to be pulled into new projects.
* The module resolver plugin seems to have introduced a [new bug](https://github.com/tleunen/babel-plugin-module-resolver/issues/144) which breaks it for our use case. I'm planning to create a minimal reproduction for them sometime soon so they can resolve this.
* After reproducing myself using `react-native-scripts@0.2.6` (which I released yesterday), I attempted to reproduce with previous scripts packages, since none of the changes I released in 0.2.6 should have affected module resolution or code transformation. I was able to reproduce with two previous versions of the scripts package, leading me to believe there was an issue with a transitive dependency and its semver bound.
* I investigated a number of recent package changes, and found that `babel-plugin-module-resolver` worked at 2.5.0, but broke at 2.6.0.
* Discussed with @brentvatne, and he released a new `babel-preset-expo` version (1.0.1) which pins the module resolver plugin to 2.5.0, and subsequently released a new `expo` version (15.1.3) which depends directly on the new preset. All new CRNA projects should pull this in by default.

I'm closing this issue, but if you run into this error again and have confirmed use of expo 15.1.3 or babel-preset-expo 1.0.1, please comment here so that I can look into it.

**Closed by dikaiosune** 2017-03-29 17:22 UTC

**Comment by adnaan** [comment] 2017-03-29 19:32
Hi,
The previous issue got resolved. Thanks for the quick response.

I think I am getting a related issue: 

```
Unable to resolve module `@expo/vector-icons/glyphmaps/Entypo.json` from `/Users/adnaan/code/expo/projects/galllery/node_modules/@expo/vector-icons/Entypo.js`: Module does not exist in the module map or in these directories:
  /Users/adnaan/code/expo/projects/galllery/node_modules/@expo/vector-icons/glyphmaps

This might be related to https://github.com/facebook/react-native/issues/4968
To resolve try the following:
  1. Clear watchman watches: `watchman watch-del-all`.
  2. Delete the `node_modules` folder: `rm -rf node_modules && npm install`.
  3. Reset packager cache: `rm -fr $TMPDIR/react-*` or `npm start --reset-cache`.

ABI15_0_0RCTFatal
ABI15_0_0RCTSetFatalHandler
ABI15_0_0RCTSetFatalHandler
<redacted>
<redacted>
_dispatch_main_queue_callback_4CF
<redacted>
<redacted>
CFRunLoopRunSpecific
GSEventRunModal
<redacted>
UIApplicationMain
Exponent
<redacted>
```

**Comment by vikkio88** [comment] 2017-03-29 19:37
I had that too @adnaan but following the suggestions of the stacktrace solved it (for me before this bug), and anyhow I think it is unrelated
```
To resolve try the following:
  1. Clear watchman watches: `watchman watch-del-all`.
  2. Delete the `node_modules` folder: `rm -rf node_modules && npm install`.
  3. Reset packager cache: `rm -fr $TMPDIR/react-*` or `npm start --reset-cache`.
```

**Comment by adnaan** [comment] 2017-03-29 19:46
@vikkio88 I tried that before. At your suggestion tried it again. It works! I am ashamed. Sorry for the noise.

**Comment by dikaiosune** [comment] 2017-03-29 21:34
@adnaan so glad you were able to resolve it!

**Comment by gnuwilliam** [comment] 2017-03-29 21:54
Thanks @dikaiosune for the quick response/fix! Great job guys, loving this project 🥇

**Comment by lukecwilliams** [comment] 2017-05-10 20:34
If you're still hitting the Entypo issue with Expo v16, it's a known issue and there's a fix here:

https://github.com/tleunen/babel-plugin-module-resolver/issues/167
