### ISSUE TITLE
Issue running Node/Express server

### ISSUE THREAD

**Issue by rcwestlake** [react-community/create-react-native-app#181] opened 2017-04-25 03:19 UTC
## Description

I am just getting started with CRNA, so please forgive me if this issue seems elementary. I am trying to connect my Node/Express server with the frontend and am getting an error which stops the processing. 

A few notes: 
- I am using the `concurrently` package to start my server and the react native scripts at the 'same' time. 
- I did some searching and haven't seen many examples of react native apps using an Express server.
- I pasted the related code below. 

## Expected Behavior

I am using a Node/Express server and Axios to make the requests. I set up a very simple initial path of `/test` and make a Get request in `componentDidMount`. I expect to see a response in the console. 

## Observed Behavior

I get an error which stops the processing. 

I am guessing my issue may be because the port and the server are not listening correctly (I noticed when I run `yarn start` that the expo port changes from 19000 to 19002. 

This is my error message:

```
8:55:05 PM: error in app.js {"line":76045,"column":24,"sourceURL":"http://10.0.0.41:19002/node_modules/react-native-scripts/build/bin/crna-entry.bundle?platform=ios&dev=true&strict=false&minify=false&hot=false&assetPlugin=expo/tools/hashAssetFiles","config":{"transformRequest":{},"transformResponse":{},"timeout":0,"xsrfCookieName":"XSRF-TOKEN","xsrfHeaderName":"X-XSRF-TOKEN","maxContentLength":-1,"headers":{"Accept":"application/json, text/plain, */*"},"method":"get","url":"/test"}}
```

## Environment

Please run these commands in the project folder and fill in their results:

* `npm ls react-native-scripts`: react-native-scripts@0.0.27
* `npm ls react-native`: react-native@0.42.3
* `npm ls expo`: expo@15.1.3
* `node -v`: v6.3.0
* `npm -v`: 4.0.5
* `yarn --version`: 0.23.2
* `watchman version`: 4.7.0

Also specify:

1. Operating system: MacOS
2. Phone/emulator/simulator & version: Expo app on iPhone SE

## Reproducible Demo

My repo: https://github.com/rcwestlake/paws. The main files are below. 

**server.js**

```
const express = require('express')
const app = express()
const bodyParser = require('body-parser')
app.use(express.static('App.js'))
app.use(bodyParser.json())
app.use(bodyParser.urlencoded({ extended: true }))

const PORT = process.env.PORT || 19000

app.set('port', PORT)
app.locals.title = 'Paws'

console.log('in the server.js file')
app.get('/test', (req, res) => {
  console.log('in the test path')
  res.send('Hello World')
})

app.listen(PORT, () => {
  console.log(`${app.locals.title} is running on ${app.get('port')}`)
})

```

When I run `yarn start` it logs the message from the `server.js` file and then starts the react-native script. 

![image](https://cloud.githubusercontent.com/assets/9679076/25367469/0e8dc220-2933-11e7-95c3-e61e6995c778.png)

**App.js**

```
import React from 'react'
import { StyleSheet, Text, View } from 'react-native'
import axios from 'axios'

class App extends React.Component {
  // --- THIS THROWS AN ERROR ---
  componentDidMount () {
    console.log('hellooooo')
    axios.get('/test')
    .then(res => console.log('res in app.js', res))
    .catch(err => console.error('error in app.js', err))
  }
  render () {
    return (
      <View style={styles.container}>
        <Text>Open up App.js to start working on your AWESOME app!</Text>
        <Text>Changes you make will automatically reload.</Text>
        <Text>Shake your phone to open the developer menu.</Text>
      </View>
    )
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: 'pink',
    alignItems: 'center',
    justifyContent: 'center'
  }
})

export default App

```

**Package.json**

```
{
  "name": "paws",
  "version": "0.1.0",
  "private": true,
  "devDependencies": {
    "concurrently": "^3.4.0",
    "jest-expo": "^0.3.0",
    "react-native-scripts": "0.0.27",
    "react-test-renderer": "~15.4.1"
  },
  "main": "./node_modules/react-native-scripts/build/bin/crna-entry.js",
  "scripts": {
    "start": "concurrently --kill-others \"react-native-scripts start\" \"node server/server.js\"",
    "eject": "react-native-scripts eject",
    "android": "react-native-scripts android",
    "ios": "react-native-scripts ios",
    "test": "node node_modules/jest/bin/jest.js --watch"
  },
  "jest": {
    "preset": "jest-expo"
  },
  "dependencies": {
    "axios": "^0.16.1",
    "body-parser": "^1.17.1",
    "expo": "^15.1.0",
    "express": "^4.15.2",
    "react": "~15.4.0",
    "react-native": "0.42.3"
  }
}
```

**Comment by jesseruder** [comment] 2017-04-25 03:31
Hello! It looks like the issue is just that you're not providing a baseURL to axios. You're calling axios with `axios.get('/test')` but it doesn't know that your server is running at localhost:19000.

**Comment by rcwestlake** [comment] 2017-04-25 03:40
Hey @jesseruder. Thanks for the response. Do I need to change the hostname like so: `REACT_NATIVE_PACKAGER_HOSTNAME='localhost'` and then call axios with `axios.get('exp://localhost:19000/test)`?

**Comment by jesseruder** [comment] 2017-04-25 03:50
Hm I'm not sure why you'd want to use `exp://`, and no don't think you need to change `REACT_NATIVE_PACKAGER_HOSTNAME`. You just need to tell axios where your express server is running.

**Comment by rcwestlake** [comment] 2017-04-25 04:02
Ahh yes, you're right. I copied the wrong thing. My current set up has the server running on port 1111. I confirmed it is working by running `node server/server.js` and going to `http://localhost:1111/test` in my browser. I see the expected output. When I add the same path to my App.js file and run it with Expo, I still get an error: 

```
 9:59:29 PM: error in app.js {"line":76043,"column":24,"sourceURL":"http://10.0.0.41:19001/node_modules/react-native-scripts/build/bin/crna-entry.bundle?platform=ios&dev=true&strict=false&minify=false&hot=false&assetPlugin=expo/tools/hashAssetFiles","config":{"transformRequest":{},"transformResponse":{},"timeout":0,"xsrfCookieName":"XSRF-TOKEN","xsrfHeaderName":"X-XSRF-TOKEN","maxContentLength":-1,"headers":{"Accept":"application/json, text/plain, */*"},"method":"get","url":"http://localhost:1111/test"}}
```

I wonder if I am missing middleware or a piece of the bundling process...

**Comment by dikaiosune** [comment] 2017-04-25 17:51
@rcwestlake sorry you're having trouble!

A couple of things I notice: it looks like you need to provide an IP address to your app for your local dev server -- 'localhost' refers to the phone when it's running on the phone. One step I'd recommend is to run the RN packager and your node server in separate tabs. It also seems like you're trying to connect directly to the RN packager rather than to your express server (port 19000 is what CRNA listens on to send your JavaScript to your phone).

Unfortunately we don't have the resources to help troubleshoot app-specific concerns like interacting with an API server, so I'm going to close this issue.

**Closed by dikaiosune** 2017-04-25 17:51 UTC

**Comment by rcwestlake** [comment] 2017-04-25 23:47
Thanks @dikaiosune. I'll give it a shot.
