### ISSUE TITLE
jest-haste-map: @providesModule naming collision

### ISSUE THREAD

**Issue by ASCE1885** [react-community/create-react-native-app#193] opened 2017-05-05 15:33 UTC
after run 'create-react-native-app my-app', and then run 'npm run ios'，I got error：

jest-haste-map: @providesModule naming collision:
  Duplicate module name: glob
  Paths: /Users/guhaoxin/Desktop/react-native-workspace/gank/node_modules/react-native/node_modules/rimraf/node_modules/glob/package.json collides with /Users/guhaoxin/Desktop/react-native-workspace/gank/node_modules/react-native/node_modules/glob/package.json

This warning is caused by a @providesModule declaration with the same name across two different files.

**Comment by ifiokjr** [comment] 2017-05-10 18:56
This seems to be a react-native and jest@20.0 issue. The same issue is affecting me when upgrading in my standard react-native app.

**Comment by kptlronyttcna** [comment] 2017-05-11 22:27
This also happens with 'react-native init' and 'run-android'

**Comment by grundmanise** [comment] 2017-05-27 15:28
similar issue but `Duplicate module name: fb-watchman` , `Duplicate module name: bser` 

```
Loading dependency graph...jest-haste-map: @providesModule naming collision:
  Duplicate module name: bser
  Paths: ...

This warning is caused by a @providesModule declaration with the same name across two different files.
jest-haste-map: @providesModule naming collision:
  Duplicate module name: fb-watchman
  Paths: ...

This warning is caused by a @providesModule declaration with the same name across two different files.
jest-haste-map: @providesModule naming collision:
  Duplicate module name: bser
  Paths: ...
```

**Comment by vesper8** [comment] 2017-05-29 06:47
having same exact problems.. this is my package.json

```
{
  "name": "xxx",
  "version": "7.0.0",
  "private": true,
  "devDependencies": {
    "babel-jest": "17.0.0",
    "babel-preset-react-native": "1.9.0",
    "chai": "^3.5.0",
    "jest": "17.0.0",
    "jest-expo": "~1.0.1",
    "jest-react-native": "17.0.0",
    "mocha": "^2.5.3",
    "react-native-scripts": "0.0.30",
    "react-test-renderer": "16.0.0-alpha.6",
    "remote-redux-devtools": "^0.3.3",
    "remote-redux-devtools-on-debugger": "^0.4.6"
  },
  "main": "./node_modules/react-native-scripts/build/bin/crna-entry.js",
  "scripts": {
    "postinstall": "remotedev-debugger",
    "start": "react-native-scripts start",
    "eject": "react-native-scripts eject",
    "android": "react-native-scripts android",
    "ios": "react-native-scripts ios",
    "test": "node node_modules/jest/bin/jest.js --watch"
  },
  "jest": {
    "preset": "jest-expo"
  },
  "dependencies": {
    "@expo/vector-icons": "~5.0.0",
    "expo": "^17.0.0",
    "lodash": "^4.13.1",
    "moment": "^2.13.0",
    "native-base": "2.1.4",
    "react": "16.0.0-alpha.6",
    "react-native": "github:exponent/react-native#sdk-17.0.0",
    "react-native-camera-roll-picker": "^1.1.9",
    "react-native-gifted-chat": "0.1.3",
    "react-native-modalbox": "^1.3.7",
    "react-native-multi-slider": "^0.3.5",
    "react-native-router-flux": "3.38.0",
    "react-native-scrollable-tab-view": "^0.7.2",
    "react-native-swiper": "^1.5.4",
    "react-redux": "^4.4.5",
    "redux": "^3.5.2",
    "redux-persist": "^3.2.2",
    "redux-thunk": "^2.1.0"
  }
}

```

**Comment by iiitmahesh** [comment] 2017-05-30 12:39
:+1:

**Comment by pbassut** [comment] 2017-05-31 03:37
same problem.

**Comment by ZevenFang** [comment] 2017-06-01 07:10
+1

**Comment by ajostergaard** [comment] 2017-06-01 20:19
https://github.com/facebook/react-native/issues/13364

**Comment by brentvatne** [comment] 2017-06-02 19:33
if you use jest-expo, don't install other versions of jest :) additionally, this is a problem with the react-native packager / haste module system that there is work in progress to attempt to resolve. it's not due to create-react-native-app itself so I'll close the issue here and you can track in the issue mentioned above by @ajostergaard

**Closed by brentvatne** 2017-06-02 19:33 UTC

**Comment by DMCHZP** [comment] 2017-09-14 10:40
+1

**Comment by dilas12345** [comment] 2018-05-05 10:54
same issue. how can i resolve it please?.

**Comment by AHStudyBank** [comment] 2018-06-28 20:28
Same issue ?? +1

**Comment by ChrisRyuGS** [comment] 2018-07-05 05:17
+1

**Comment by nicsptl** [comment] 2018-07-31 21:45
For me Problem was, watchman path in windows environment variables. Removing that unused path fixed problem for me. Hope this helps to someone.

**Comment by yarra2296** [comment] 2018-08-09 10:26
@ajostergaard , 
Is the issue solved? can I know the solution?

**Comment by dilas12345** [comment] 2018-08-16 22:14
Let me know in details. Is this the first time you are starting that project entirely? that will make me know where we could really pin point where the problem is coming from.

**Comment by ganesh-pprasad** [comment] 2018-09-04 06:04
I am facing the issue on RN 0.56 and xcode 9.4.
I tried giving the path for React in my pod file to node_modules/react-native but still it installs a React folder to pods/ .
Can someone please explain how to fix this bug

**Comment by ameshkin** [comment] 2018-09-14 19:02
I had this same problem as well but was able to fix it by removing pod files installed in ios/Pods

And then clearing cache

**Comment by shinriyo** [comment] 2018-09-26 00:01
@ameshkin 
`rm -rf ios/Pods`
`pod install`

how to clear cache?

**Comment by shinriyo** [comment] 2018-09-26 00:06
`ios/Podfile`

I commented out it. I didn't wrote the line but it automatically wrote...
```
  # pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'
``

and `pod install` again. it works.
